### ISSUE TITLE
weird recaptcha error

### ISSUE THREAD

**Issue by cxhernandez** [cxhernandez/slack-butler#2]
Might be an issue with my api token... TBD

```
TypeError: Property 'next' of object #<IncomingMessage> is not a function
    at fn (/Users/cu3alibre/Developer/slack-butler/node_modules/express/lib/response.js:933:25)
    at EventEmitter.app.render (/Users/cu3alibre/Developer/slack-butler/node_modules/express/lib/application.js:568:5)
    at ServerResponse.res.render (/Users/cu3alibre/Developer/slack-butler/node_modules/express/lib/response.js:938:7)
    at EventEmitter.<anonymous> (/Users/cu3alibre/Developer/slack-butler/app.js:75:9)
    at EventEmitter.emit (events.js:117:20)
    at EventEmitter.reCaptcha.checkAnswer (/Users/cu3alibre/Developer/slack-butler/node_modules/recaptcha-async/lib/recaptcha.js:74:8)
    at /Users/cu3alibre/Developer/slack-butler/app.js:84:13
    at Layer.handle [as handle_request] (/Users/cu3alibre/Developer/slack-butler/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/cu3alibre/Developer/slack-butler/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/Users/cu3alibre/Developer/slack-butler/node_modules/express/lib/router/route.js:91:3)
```

**Comment by cxhernandez** [comment]
from [L82](https://github.com/cxhernandez/slack-butler/blob/captcha/app.js#L82)

**Comment by cxhernandez** [comment]
Solved in https://github.com/cxhernandez/slack-butler/pull/3
